---
- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Check if port 80 is open
  ansible.builtin.wait_for:
    port: 80
    state: absent
    timeout: 10

